### ISSUE TITLE
More clarification on room creation.

### ISSUE THREAD

**Issue by Sadmansamee** [GursheeshSingh/chat_screen_flutter#1]
Excelent work, would you like to clarify more on how to create Room?

**Comment by GursheeshSingh** [comment]
For Firebase?

**Comment by Sadmansamee** [comment]
for parse

**Comment by GursheeshSingh** [comment]
Did you try the setup instructions in README?

**Comment by Sadmansamee** [comment]
where would I get room ID? and how it will be generated, that was my confusion

**Comment by GursheeshSingh** [comment]
Okay.

You can randomly generate it and save on your server
or you can use an existing ID.

Example: Lets say you have an app which a list of college with each college having a unique ID, you can use the college ID as room id.

**Comment by Sadmansamee** [comment]
ah, got it, thanks.
